language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli

before_deploy:
  - openssl aes-256-cbc -K $encrypted_352c24ac275b_key -iv $encrypted_352c24ac275b_iv -in mes-aides-bot.enc -out mes-aides-bot.key -d
  - chmod 600 mes-aides-bot.key
deploy:
  skip_cleanup: true  # prevent stashing the decrypted key out
  provider: script
  script: ssh -i mes-aides-bot.key deploy@mes-aides.gouv.fr ./deploy.sh
  on:
    branch: master
