apps:
  - name: ma-web
    script   : server.js
    instances: 1
    exec_mode: cluster
    merge_logs: true
    env:
        MES_AIDES_ROOT_URL: https://next.mes-aides.gouv.fr
        MONGODB_URL: mongodb://localhost/dds
        NODE_ENV: production
        PORT: 8000
        CHROME_DEVEL_SANDBOX: /usr/local/sbin/chrome-devel-sandbox
